package.json
pnpm-lock.yaml
tests/specs/json.ts

Tests are outdated for JSON named imports
- Updates semver range floor for `esm-loader`
- Updates tests to support JSON named imports
This doesn't necessarily have to be a `feat` because this feature in `esm-loader` is included the range, but figured why not to make the feature definitely installable.

feat: support named imports for json modules

---

README.md
package.json
pnpm-lock.yaml
src/cli.ts
src/repl.ts

Previously, the REPL did not support TypeScript or any other transformations
closes https://github.com/esbuild-kit/esno/issues/20
Applies all transformations to REPL pre-evaluation

feat: TypeScript REPL

---

package.json

fix https://github.com/esbuild-kit/esno/issues/29

fix: expose `cli` module

---

package.json
pnpm-lock.yaml
tests/specs/typescript/ts.ts

closes https://github.com/esbuild-kit/tsx/issues/18

fix(typescript): resolve js to ts

---

src/repl.ts
tests/index.ts
tests/specs/repl.ts

TypeScript REPL can't actually execute TypeScript expressions
It detected a wrong loader(`js`) because in [core-utils](https://github.com/esbuild-kit/core-utils/blob/7348ce37265de7b76be726b9c4e6e335e65be6c0/src/transform/get-esbuild-options.ts#L35) that `path.extname('.ts')` returns an empty string, so it will add a `.js` suffix to the `filePath`and then a `js` loader is detected.
see [transform/get-esbuild-options.ts#L35](https://github.com/esbuild-kit/core-utils/blob/7348ce37265de7b76be726b9c4e6e335e65be6c0/src/transform/get-esbuild-options.ts#L35)
there's also another solution I prefer:
```js
transform(code, 'repl', { loader: 'ts' })
```

fix(repl): specify ts loader

---

package.json

Like use :
```ts
require.resolve('tsx/package.json')
```
Need export `package.json` subpath, otherwise an error will be thrown.
A real example : https://github.com/umijs/umi/pull/9152/files#diff-faa31e153df54d7263fcc895970fea96ab82253e8943d08d85ea22b49338ac0fR53

feat: add `package.json` subpath export

---

README.md

I wanted to :heart: tsx, but the lack of support for decorators (see #37) is a significant and unfortunate blocker.
I spent some effort testing a NestJs project with tsx and debugging why it didn't work before I learned this fact. Having this information available from the start would have saved me some time, so for the benefit of others I suggest adding it to the project README.

docs: add section on limitations

---

src/watch/index.ts
tests/specs/watch.ts

When using relative paths with `watch --ignore`, chokidar won't pick up the correct files.
The existing test is refactored to use relative paths instead of absolute paths to ignore and execute. 
The fix is to explicitly provide a `cwd` to chokidar.
**Reproduction**: open [stackblitz](stackblitz.com/edit/node-q34cum?file=index.js&view=editor), run `pnpm dev` and change something in `ignored.js`. `tsx` should not rerun, but does.

fix(watch): relative paths in --ignore flag

---

src/preflight.cts

closes https://github.com/esbuild-kit/tsx/issues/122
This changes hides tsx's signal listeners in case other code tries to do the same thing. In this case, Prim's client code added a hook that also only exists if it's the only handler:
https://github.com/prisma/prisma/blob/4732879b2bf81d7960df435cfb22a4a32eaa028c/packages/engine-core/src/library/ExitHooks.ts#L62

fix: hide process signal handler

---

src/cli.ts
src/loader.ts
src/patch-repl.ts
src/repl.ts
tests/index.ts
tests/specs/repl.ts
tests/utils/tsx.ts

Previously, tsx was creating it's own REPL, which diverged and lacked functionality from Node.js's default REPL. This also required that tsx re-implement flag handling logic to match Node.js.
Instead of creating a new REPL, patch Node.js' so that we get Node.js's better REPL for free and also delegate handling the command line flags.
Since we are no longer handling how Node.js should interpret command-line flags, this may benefit https://github.com/esbuild-kit/tsx/pull/111

refactor: patch Node.js REPL to add TypeScript support

---

src/preflight.cts
tests/fixtures/log-argv.ts
tests/specs/typescript/ts.ts
tests/utils/tsx.ts

fix https://github.com/esbuild-kit/tsx/issues/124

feat: support transforming via require flag

---

src/watch/index.ts
tests/specs/watch.ts

`dist` directory was ignored from watch. This made it difficult to pair tsx with programs that built source files.
For example, when developing an ESLint config, ESLint handles loading the config modules, so they must be built to CommonJS. (There's no way to override the default `require` hook because ESLint tries to handle different extensions on its own.) When testing the config, the test files would be importing from the `dist` directory.
Remove `dist` from watch ignore list.

fix(watch): remove `dist` from ignore

---

src/preflight.cts

Closes #193 
Continues the approach from #123 and hides the `relaySignal` listener added by tsx from `process.listeners()` which is what the signal-exit module uses to determine whether to proceed with exiting the program. I've tested and confirmed that it fixes the issue.
https://github.com/tapjs/signal-exit/blob/8d4bd9c/index.js#L121

fix: hide relaySignal from `process.listeners()`

---

src/utils/transform/cache.ts

If you use `tsx` in a Unix environment where different users are executing `tsx` at the same time, you'll end up trying to share `/tmp/tsx`.
```bash
Error: EACCES: permission denied, scandir '/tmp/tsx'
```
This attempts to resolve that problem by using the executing `uid` in the cache directory name.
Seeing as the unix permissions of the `/tmp/tsx` directory already has the `uid` as meta information, this doesn't reveal anything new, but it does prevent the naming conflict.
```node
> path.join(os.tmpdir(), `tsx-${os.userInfo().uid}`)
'/tmp/tsx-1000'
```
I don't know what behavior this will have on non-unix systems

fix(cache): scope cache directory to user

---

src/cjs/index.ts
src/esm/loaders.ts
src/esm/utils.ts
src/source-map.ts
src/utils/debug.ts
src/utils/esm-pattern.ts

If source maps are not enabled by the user, strip all source maps so it speeds up processing. Results seem marginal but better than nothing.
Also note, stripping source maps has notable performance gains in v18. Unfortunately, `process.sourceMapsEnabled` isn't available in v18 so we're not able to make this improvement there.
related https://github.com/esbuild-kit/tsx/issues/285

perf: strip source map when unused

---

README.md

Added short description in the readme on how to setup debugging in VS Code (#267)

docs: VS Code debugging

---

src/esm/register.ts
src/watch/index.ts
src/watch/utils.ts
tests/specs/watch.ts

fix https://github.com/privatenumber/tsx/issues/218
In addition, this improves child process exit handling:
- When a reload is triggered, it sends `SIGTERM` to the child, but if it doesn't exit within 5s, it sends a `SIGKILL`
- When the watcher is exiting (e.g. Ctrl+C), it sends a `SIGKILL` if it doesn't exit within 5s
- The rationale here is that you're quitting the watcher instead of the process. And it doesn't make sense that the child process can trap the watcher and prevent it from exiting.
- Double Ctrl+C to force quit

feat(watch): log reason for rerun & improved exit handling

---

package.json
pnpm-lock.yaml

With https://github.com/evanw/esbuild/issues/3353 sorted out, we're now ready for esbuild v0.19 🎉 
- esbuild [v0.19.0](https://github.com/evanw/esbuild/releases/tag/v0.19.0) contains some backwards-incompatible changes, but I doubt those are affecting projects using `tsx` in most cases
- Signature / types are still the same and compatible
- Tests are successful
Closes #408

feat: upgrade esbuild to v0.19.10

---

.github/workflows/lock-threads.yml

The current syntax for the lock threads job is incorrect. This PR addresses it.
Also, add actionlint to check job syntax as part of the PR workflow.
Finally, format syntax as suggested by actionlint.
Refs: https://github.com/privatenumber/tsx/pull/441

ci(lock-threads): fix yaml syntax

---

README.md

The `workspaceRoot` variable is deprecated and replaced with the `workspaceFolder` variable, in reference to Multi-Folder workspaces that don't have a root
https://code.visualstudio.com/docs/editor/variables-reference#_why-isnt-workspaceroot-documented

docs(VS Code): replaced `workspaceRoot` with `workspaceFolder`

---

src/utils/transform/index.ts
tests/specs/cli.ts
tests/specs/transform.ts

Closes #473 
When path had a single quote it was breaking the path passed to esbuild.
Added passing tests. 
Locally using node from nvmrc there were 3 tests not passing.
But passing in node v18.15.0

fix: escape `import.meta.url` passed to esbuild

---

README.md

There is also a [variant](https://stackoverflow.com/a/52979955/808699) with `-S`:
```bash
#!/usr/bin/env -S npx tsx
```
but as per my testing using BSD and GNU `env`, the two variants work exactly the same, so I guess without the `-S` would be slightly more portable.

docs: Add example for hashbang with local tsx

---

README.md

Turns out there is a behaviour difference in the GNU `env` tool between MacOS and Linux where the latter does require `-S` for it to work. I've confirmed this working now with:
- env (GNU coreutils) 9.5 on MacOS 14
- env (GNU coreutils) 9.5 on Arch Linux
- env (BSD) on MacOS 14
I posted this as an answer one https://stackoverflow.com/questions/55777677. Also see https://github.com/TypeStrong/ts-node/issues/639#issuecomment-538984217 for similar solution.

docs: fix hashbang example for linux env command

---

src/esm/hook/resolve.ts
tests/specs/api.ts
tests/specs/smoke.ts

This PR attempts to fix the issue described here: https://github.com/privatenumber/tsx/issues/543

fix(esm): resolve absolute paths

---

.github/workflows/release.yml
.github/workflows/test.yml
package.json

This would allow contributors to have the exactly same version of pnpm (with corepack enabled).
Also the pnpm setup action will read that field, so we have a single source of the pnpm versions

chore: add `packageManager` field to for explicit pnpm version

---

.gitignore

Not sure if it's only me, but I got these in the git status:

chore: update `gitignore`

---

src/esm/api/index.ts
src/esm/api/register.ts

I was using `ReturnType<typeof register>` to get the type - which I wasn't able to get the overloads with namespaced one. I think it would be nice to expose them.

fix: expose types for `esm/api`

---

package.json

Currently the resolved types for `tsx/cjs/api` are broken/wrong for some `moduleResolution`s. Also, resolve to `dist/cjs/api/index.mjs` when `import`ed.

fix(cjs/api): resolve correct module and types when imported

---

docs/node/esm.md

docs: remove duplicate `Tracking loaded files` section

---

src/esm/api/register.ts

According to https://nodejs.org/api/module.html#moduleregisterspecifier-parenturl-options
Module.register was Added in: v20.6.0, v18.19.0

fix: minimum Node version in warning for `module.register()`

---

eslint.config.js
package.json

Putting the ESLint config in `eslint.config.js` makes it discoverable by editor integrations so that they can show lint errors/fixes inline.
AFAICT `lintroll` completely ignores the `eslintConfig` property in `package.json`, so it already wasn't necessary (and there wasn't a `@pvtnbr/*` package installed to begin with). The ignore of `tests/fixtures`, despite being ignored in the first place, also just isn't necessary.

chore: remove unused `eslintConfig`

---

src/utils/transform/get-esbuild-options.ts

This PR attempts to fix the issue described here: #661 
If make changes to `tsx/src/run.ts`, the `--inspect` flag will be confused with the flag of the custom program.
```sh
// run command
./dist/cli.mjs --inspect temp/test.ts --inspect-xxx
// tsx/src/run.ts
// `console.log(argv)`
[ '--inspect', 'temp/test.ts', '--inspect-xxx' ]
```
But in `src/utils/transform/get-esbuild-options.ts`, `process.execArgv` doesn't have this problem
```sh
// run command
./dist/cli.mjs --inspect temp/test.ts --inspect-xxx
// src/utils/transform/get-esbuild-options.ts
// `console.log(process.execArgv)`
[
'--require',
'/home/debian/tsx/dist/preflight.cjs',
'--import',
'file:///home/debian/tsx/dist/loader.mjs',
'--inspect'
]
```

fix: generate sourcesContent when Node.js debugger is enabled

---

docs/getting-started.md

This PR updates links to `npx` on page https://tsx.is/getting-started
Actual version of `npx` page is `https://docs.npmjs.com/cli/v10/commands/npx/`, but variant without version number (`https://docs.npmjs.com/cli/commands/npx/`) is also supported, this URL redirects to current version.
So I think using the `https://docs.npmjs.com/cli/commands/npx/` is the best choice.

docs: update links to `npx`

---

package.json
pnpm-lock.yaml

Fixes [GHSA-67mh-4wv8-2f99](https://github.com/advisories/GHSA-67mh-4wv8-2f99)
https://github.com/evanw/esbuild/releases/tag/v0.25.0
I ran the tests manually and they succeeded.

fix: upgrade `esbuild` to `~0.25.0` to address vuln report

---

package.json
pnpm-lock.yaml
src/utils/es-module-lexer.ts
tests/specs/api.ts
tests/specs/smoke.ts

When running Node with `--jitless`, WebAssembly is unavailable. I have a (weird) benchmark-related use-case for it, but because of `es-module-lexer` it is currently not working.
This PR makes the WebAssembly lexer import gated behind a check, so it gracefully falls back to the plain js implementation in this scenario.
I also tucked in a workaround for an issue with node-gyp and node-pty, as well as upgrading pnpm. 😄

fix: support for --jitless
